### ISSUE TITLE
rtol=1 seems dangerous

### ISSUE THREAD

**Issue by eford** [PsuAstro528/project-elizabethg60#55]
https://github.com/PsuAstro528/project-elizabethg60/blob/5c78e85793f46d7facc0eda92a67eb8fafac6217/src/test/runtests.jl#L37
When comparing serial and parallel, I'd hope that they agree to much better than rtol=1!
(For the previous tests, I didn't follow enough to know what was reasonable.)

**Comment by elizabethg60** [comment]
should have been 0.1 - corrected!
